theme: jekyll-theme-cayman
title: nginx-php7
description: Nginx PHP7 for Docker
encoding: UTF-8
highlighter: rouge

author:
github: skiy

copyright:
year: 2018-2019
name: Skiychan

timezone: Asia/Shanghai